### ISSUE TITLE
Feature: User can create a project board

### ISSUE THREAD

**Issue by yunyunliu** [yunyunliu/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a project board
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user clicks the plus icon in projects view to generate a new project with the default name of 'new board' 
user can click on the board name text to show a text input where they can enter a different name. and a button that on click submits name change

Attach event handler that creates a new board to plus icon, which makes request to server to make a new board 
Have a 'isEditing' value in state that can be toggled, which will determine whether text input box or project name is rendered

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
[figma](https://www.figma.com/file/DDV9GoV1xMNSAWEDj1mE9A/Yunyun-Liu---Final-Project?node-id=1%3A4)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

no changes needed

### ☁️ Server

- [ ] create endpoint to receive post request
- [ ] create request handler that makes a INSERT query to database for a new board and sends new record in response

- [ ] Handle all errors and send newly created record in response

### ⚡ Client

- [ ] create and style  <Board> component 
- [ ] Create and style  <Add> component containing a button that onClick  sends api request
- [ ] after successful api request, page is updated to display new board

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
