### ISSUE TITLE
Feature: User can edit a board name

### ISSUE THREAD

**Issue by yunyunliu** [yunyunliu/Final-Project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can click on the board name text to show a text input where they can enter a different name. and a button that on click submits the name change to server and replaces the text input with the new board name

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user input into text box stored in state; onclick api request to update

## 🖼️ Wireframes

[figma](https://www.figma.com/file/DDV9GoV1xMNSAWEDj1mE9A/Yunyun-Liu---Final-Project?node-id=1%3A4)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

no changes needed

### ☁️ Server

- [ ] add patch endpoint that makes update query to server using the data and boardId provided in request
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Add html and styling for input element and button for where user will enter new board name
- [ ] style project buttons
- [ ] add piece of state that keeps track of the boardId that is being edited
- [ ] add handler to project buttons that sets the id of the board clicked on as currentlyEditing value of state
- [ ] add click handler to confirm button, which send patch request to server with the text input value in it's body 
- [ ] on successful api request set currentlyEditing back to null, set new value or boards with the updated board 

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
