### ISSUE TITLE
Feature: User can delete a board

### ISSUE THREAD

**Issue by yunyunliu** [yunyunliu/Final-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can click close icon at the corner of a board in project view to have a modal appear asking to confirm delete 
user can click delete to delete board and exit modal or click cancel exit modal without deleting

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

add delete button that makes api request server to delete board and all the columns and cards it contains from database. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

[figma](https://www.figma.com/file/DDV9GoV1xMNSAWEDj1mE9A/Yunyun-Liu---Final-Project?node-id=1%3A4)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

no changes necessary

### ☁️ Server

- [ ]  create endpoint for delete method
- [ ] figure out how to delete all columns, cards and tags associated with a board
- [ ] add handler that makes DELETE query to database with the boardId provided by request
- [ ]  check that endpoints and sql work
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] create and style confirm modal component
- [ ] add handler to close icon of <Board>  component that displays confirm modal onClick
- [ ]  add handlers to delete and cancel buttons on confirm modal
    - [ ] confirm button handler makes api request to server, updates page when it gets a successful response, and exits modal
    - [ ] cancel button-handler exits modal

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
